version: '3'

services:
    web:
        image: nginx:1.16.1
        container_name: wp_nginx1.6
        restart: on-failure
        ports:
            - "5000:80"
        volumes:
            - ./www:/var/www
            - ./nginx1.6/site.conf:/etc/nginx/conf.d/site.conf
        working_dir: /var/www
        networks:
          backend:
            ipv4_address: 172.16.238.10

    php:
        build:
            context: ./php/7.4
            dockerfile: Dockerfile
        container_name: wp_php7.4
        volumes:
            - ./www:/var/www
        networks:
          backend:
            ipv4_address: 172.16.238.11

    db:
        image: mysql:5.7
        container_name: wp_mysql5.7
        ports:
            - "3306:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_USER=root
            - MYSQL_DATABASE=wordpress
        volumes:
            - ./mysql-data:/var/lib/mysql
        networks:
          backend:
            ipv4_address: 172.16.238.12

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: wp_phpmyadmin
        ports:
            - "8888:80"
        environment:
            - PMA_HOST=172.16.238.1
        networks:
          backend:
            ipv4_address: 172.16.238.13

networks:
    backend:
        ipam:
            driver: default
            config:
                - subnet: "172.16.238.0/24"
